config/routes.rb
Taradai::Application.routes.draw do

  get "placesprof/index"

  get "placesprof/new"

  get "placesprof/create"

  get "placesprof/edit"

  get "placesprof/update"

  get "placesprof/delete"

  get "placesprof/destroy"

  get "events/my_events_create"

  get "events/my_events_new"

  get "events/my_events_edit"

  get "events/my_events_update"

  get "events/my_events_delete"

  get "events/my_events_destroy"

  get "events/group_events"

  get "events/group_events_new"

  get "events/group_events_create"

  get "events/group_events_edit"

  get "events/group_events_update"

  get "events/group_events_delete"

  get "events/group_events_destroy"

  get "events/tendency_events"

  devise_for :users
  
  resources :profiles, :only => [:new, :create, :edit, :update]
  resources :pendings, :only => [:create, :delete]
  resources :messages, :only => [:create]
  
  match 'map',                                              :controller => 'maps',             :action => 'random',              :as => 'maps_random'
  match 'my/map(.:format)',                                 :controller => 'maps',             :action => 'query',               :as => 'maps_query'
  match 'my/localization(.:format)',                        :controller => 'maps',             :action => 'localization',            :as => 'maps_location'
  match 's',                                                :controller => 'search',           :action => 'form',                :as => 'search_form'
  match 's/results',                                        :controller => 'search',           :action => 'results',             :as => 'search_results'
  
  match 'my/locale/:locale',                                :controller => 'locale',           :action => 'change',              :as => 'locale'
  
  match 'my/netupdates.:format',                            :controller => 'network',          :action => 'updates',             :as => "network_updates"
  match ':profilename/updates.:format',                     :controller => 'prof',             :action => 'updates',             :as => "profile_updates"
  
  match 'my/notifications/preview',                         :controller => 'notifications',    :action => 'preview',             :as => 'notifications_preview'
  match 'my/notifications',                                 :controller => 'notifications',    :action => 'index',               :as => 'notifications_index'
    
  
  match 'my/blog',                                          :controller => 'blogs',            :action => 'index',               :as => 'blog_my'
  match 'my/blog/new',                                      :controller => 'blogs',            :action => 'new',                 :as => 'blog_new'
  match 'my/blog/create',                                   :controller => 'blogs',            :action => 'create',              :as => 'blog_create'
  match 'my/blog/:slug/',                                   :controller => 'blogs',            :action => 'read',                :as => 'blog_read'
  match 'my/blog/:slug/edit',                               :controller => 'blogs',            :action => 'edit',                :as => 'blog_edit'
  match 'my/blog/:slug/update',                             :controller => 'blogs',            :action => 'update',              :as => 'blog_update'
  match 'my/blog/:slug/delete',                             :controller => 'blogs',            :action => 'delete',              :as => 'blog_delete'
  match 'my/blog/:slug/destroy',                            :controller => 'blogs',            :action => 'destroy',             :as => 'blog_destroy'
  
  match ':profilename/blog',                                :controller => 'blogs',            :action => 'browse',              :as => 'blogs_show'
  match ':profilename/blog/:slug',                          :controller => 'blogs',            :action => 'show',                :as => 'blog_show'
    
  match 'my/messages/inbox',                                :controller => 'messages',         :action => 'inbox',               :as => 'messages_inbox'
  match 'my/messages/preview',                              :controller => 'messages',         :action => 'preview',             :as => 'messages_preview'
  match 'my/messages/inbox/:slug',                          :controller => 'messages',         :action => 'read_inbox',          :as => 'message_read_inbox'
  match 'my/messages/inbox/delete/:slug',                   :controller => 'messages',         :action => 'delete_inbox',        :as => 'message_delete_inbox'
  match 'my/messages/inbox/destroy/:slug',                  :controller => 'messages',         :action => 'destroy_inbox',       :as => 'message_destroy_inbox'
  match 'my/messages/outbox',                               :controller => 'messages',         :action => 'outbox',              :as => 'messages_outbox'
  match 'my/messages/new',                                  :controller => 'messages',         :action => 'new',                 :as => 'message_new'
  match 'my/messages/reply/:slug',                          :controller => 'messages',         :action => 'reply',               :as => 'message_reply'
  match 'my/messages/outbox/:slug',                         :controller => 'messages',         :action => 'read_outbox',         :as => 'message_read_outbox'
  match 'my/messages/outbox/delete/:slug',                  :controller => 'messages',         :action => 'delete_outbox',       :as => 'message_delete_outbox'
  match 'my/messages/outbox/destroy/:slug',                 :controller => 'messages',         :action => 'destroy_outbox',      :as => 'message_destroy_outbox'
  
  match 'my/friends/accept/:id',                            :controller => 'pendings',         :action => 'accept',              :as => 'friend_accept'
  match 'my/friends/ignore/:id',                            :controller => 'pendings',         :action => 'ignore',              :as => 'friend_ignore' 
  match 'my/friends/list.:format',                          :controller => 'friends',          :action => 'list',                :as => 'friend_list'
  match 'my/friends/requested',                             :controller => 'pendings',         :action => 'requested',           :as => 'friend_requested'
  match 'my/friends/requests',                              :controller => 'pendings',         :action => 'index',               :as => 'friend_requests' 
  match 'my/friends/request/:profilename',                  :controller => 'friends',          :action => 'req',                 :as => 'friend_request'
  
  match ':profilename/portrait/new',                        :controller => 'portrait',         :action => 'new',                 :as => 'portrait_new'
  match ':profilename/portrait/create',                     :controller => 'portrait',         :action => 'create',              :as => 'portrait_create'
  match ':profilename/portrait/delete',                     :controller => 'portrait',         :action => 'delete',              :as => 'portrait_delete'
  match ':profilename/portrait/destroy',                    :controller => 'portrait',         :action => 'destroy',             :as => 'portrait_destroy'
  
  match ':profilename/status/new',                          :controller => 'statuses',         :action => 'new',                 :as => 'status_new'
  match ':profilename/status/change',                       :controller => 'statuses',         :action => 'create',              :as => 'status_create'
  
  match ':profilename/photos',                              :controller => 'photos',           :action => 'show',                :as => 'photos_show'
  match ':profilename/photos/album/new',                    :controller => 'photos',           :action => 'album_new',           :as => 'album_new'
  match '/photos/album/create',                             :controller => 'photos',           :action => 'album_create',        :as => 'album_create'
  match ':profilename/photos/album/:slug',                  :controller => 'photos',           :action => 'album_show',          :as => 'album_show'
  match ':profilename/photos/album/:slug/organize',         :controller => 'photos',           :action => 'album_organize',      :as => 'album_organize'
  match ':profilename/photos/album/:slug/delete',           :controller => 'photos',           :action => 'album_delete',        :as => 'album_delete'
  match ':profilename/photos/album/:slug/deleteit',         :controller => 'photos',           :action => 'album_deleteit',      :as => 'album_deleteit'
  match ':profilename/photos/album/:slug/org',              :controller => 'photos',           :action => 'album_org',           :as => 'album_org'
  match '/photos/album/:slug/cover/:id',                    :controller => 'photos',           :action => 'album_cover',         :as => 'album_cover'
  match '/photos/album/:slug/newcover/:id',                 :controller => 'photos',           :action => 'album_newcover',      :as => 'album_change_cover'
  match '/photos/album/:slug/delete/:id',                   :controller => 'photos',           :action => 'photo_delete',        :as => 'photo_delete'
  match '/photos/album/:slug/deleteit/:id',                 :controller => 'photos',           :action => 'photo_deleteit',      :as => 'photo_deleteit'
  match ':profilename/photos/album/:slug/new',              :controller => 'photos',           :action => 'photo_new',           :as => 'photo_new'
  match ':profilename/photos/album/:slug/:id',              :controller => 'photos',           :action => 'photo_show',          :as => 'photo_show'
  match '/photos/create',                                   :controller => 'photos',           :action => 'photo_create',        :as => 'photo_create'

  match '/my/events',                                       :controller => 'events',           :action => 'my_events',           :as => 'profile_my_events'

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def form
    render :layout => 'none'
  end
  
  def results
    # if query is html....
    if params[:for].nil? == false and params[:search].nil? == false
      @for = params[:for]
      @search_terms = params[:search]
      session[:for] = @for
      session[:search_terms] = @search_terms
    else
      # if query is ajax.....
      if session[:for].nil? == false and session[:search_terms].nil? == false 
        @for = session[:for]
        @search_terms = session[:search_terms]
        puts '------------------------------------------------------------------paso'
      end
    end
        
    if @for == 'people' or @for == 'groups'
      if @search_terms.nil? == false
        case @for
        when 'people'
          @search = Profile.search(@search_terms).paginate(:per_page => 20, :page => params[:page])
        end
      end
    end
    
    @profile = @current_profile
    render :layout => 'profile'
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_profile_results.html.erb
<%= will_paginate(@search) %>
<ul id="search_results">
<% @search.each do |search| %>
	<li>
		<% friend = @current_profile.connected?('Friend', search) %>
		<div class="left w70"><%= link_to image_tag(file_path(search.portrait, 'portrait', '50'), :alt=> search.name, :class => 'm10'), profile_show_url(:profilename => search.profilename) %></div>
		<div class="left w430 f105 m10"><%= link_to search.name, profile_show_url(:profilename => search.profilename) %><%= " (amigo)" if friend %><%= " (tú)" if search == @current_profile %>
			<br />
			<div id="hideable" class="right">
			<% if search != @current_profile and friend == false %>
				<%= link_to 'Añadir como amigo', friend_request_url(:profilename => search.profilename), :class => 'button mr0 ml0', :type => 'modal' %>
			<% end %>
			</div>
		</div>
	</li>
<% end %>
</ul>
<%= will_paginate(@search) %>

app/views/search/form.html.erb
<% content_for :content do %>
<div class="w470">
	<%= form_tag(search_results_url, :method => 'post') %>
	<div class="w460 radius4 green0f green4b f130 lh130 p5 mr0">Buscar en taradai</div>
	<div class="w460 fcolor8 f110 lh110 mt10"><p>Utiliza este formulario para buscar en taradai. Selecciona qué quieres buscar y escribe los criterios de búsqueda.</p></div>
	
	<div class="w460 fcolor9 f110 lh110 mt10">
		<div class="w70 mr10 tright left mb10"><strong>¿Qué buscas?</strong></div>
	
		<div class="w370 right mb10">
			<%= select_tag :for, options_for_select([['Gente', 'people'], ['Grupos','groups']], 'people')  %>
		</div>
		<div class="clear">
		<div class="w70 mr10 tright left"><strong>Búsqueda:</strong></div>
	
		<div class="w370 right">
			<%= text_field_tag 'search', '' %>
		</div>
	</div>
	<div class="clear"></div>
	<div class="mt10 w540">
		<div class="right">
	<input type="button" value="Cancelar" class="close" />
	<%= submit_tag 'Buscar', :class => 'ml10' %>
		</div>
	</div>
	</form>
	<div class="clear"></div>
</div>
<% end %>

app/views/search/results.html.erb
<% content_for :main do %>
<%= form_tag(search_results_url, :method => 'post') %>
<div class="w530 green4b green0f radius4">
	<div class="m10">
		<div class="clear w100 m10 tright left"><%= select_tag :for, options_for_select([['Gente', 'people'], ['Grupos','groups']], 'people')  %></div>
		<div class="w380 left m10"><%= text_field_tag 'search', "#{@search_terms}", :class => 'left' %><%= submit_tag 'Buscar', :class => 'ml120 gside' %></div>
		</form>
		<div class="clear"></div>
		</div>
</div>

	<% if @search.nil? == false %>
		<% case @for %>
		<% when 'people' %>
			<div class="w530 left radius4 green3b green0f mb10">
				<div class="m5 b"><%= "Resultados de tu búsqueda '#{@search_terms}'." %></div>
			</div>
			<div id="results" class="clear">
				<%= render :partial => 'profile_results' %>
			</div>
		<% end %>
	<% else %>	
		<%= "search is nil!!"%>
	<% end %>
<% end %>

app/views/search/results.js.erb
$("div#results").html("<%= escape_javascript(render('profile_results'))%>");