config/routes.rb
Taradai::Application.routes.draw do

  get "placesprof/index"

  get "placesprof/new"

  get "placesprof/create"

  get "placesprof/edit"

  get "placesprof/update"

  get "placesprof/delete"

  get "placesprof/destroy"

  get "events/my_events_create"

  get "events/my_events_new"

  get "events/my_events_edit"

  get "events/my_events_update"

  get "events/my_events_delete"

  get "events/my_events_destroy"

  get "events/group_events"

  get "events/group_events_new"

  get "events/group_events_create"

  get "events/group_events_edit"

  get "events/group_events_update"

  get "events/group_events_delete"

  get "events/group_events_destroy"

  get "events/tendency_events"

  devise_for :users
  
  resources :profiles, :only => [:new, :create, :edit, :update]
  resources :pendings, :only => [:create, :delete]
  resources :messages, :only => [:create]
  
  match 'map',                                              :controller => 'maps',             :action => 'random',              :as => 'maps_random'
  match 'my/map(.:format)',                                 :controller => 'maps',             :action => 'query',               :as => 'maps_query'
  match 'my/localization(.:format)',                        :controller => 'maps',             :action => 'localization',            :as => 'maps_location'
  match 's',                                                :controller => 'search',           :action => 'form',                :as => 'search_form'
  match 's/results',                                        :controller => 'search',           :action => 'results',             :as => 'search_results'
  
  match 'my/locale/:locale',                                :controller => 'locale',           :action => 'change',              :as => 'locale'
  
  match 'my/netupdates.:format',                            :controller => 'network',          :action => 'updates',             :as => "network_updates"
  match ':profilename/updates.:format',                     :controller => 'prof',             :action => 'updates',             :as => "profile_updates"
  
  match 'my/notifications/preview',                         :controller => 'notifications',    :action => 'preview',             :as => 'notifications_preview'
  match 'my/notifications',                                 :controller => 'notifications',    :action => 'index',               :as => 'notifications_index'
    
  
  match 'my/blog',                                          :controller => 'blogs',            :action => 'index',               :as => 'blog_my'
  match 'my/blog/new',                                      :controller => 'blogs',            :action => 'new',                 :as => 'blog_new'
  match 'my/blog/create',                                   :controller => 'blogs',            :action => 'create',              :as => 'blog_create'
  match 'my/blog/:slug/',                                   :controller => 'blogs',            :action => 'read',                :as => 'blog_read'
  match 'my/blog/:slug/edit',                               :controller => 'blogs',            :action => 'edit',                :as => 'blog_edit'
  match 'my/blog/:slug/update',                             :controller => 'blogs',            :action => 'update',              :as => 'blog_update'
  match 'my/blog/:slug/delete',                             :controller => 'blogs',            :action => 'delete',              :as => 'blog_delete'
  match 'my/blog/:slug/destroy',                            :controller => 'blogs',            :action => 'destroy',             :as => 'blog_destroy'
  
  match ':profilename/blog',                                :controller => 'blogs',            :action => 'browse',              :as => 'blogs_show'
  match ':profilename/blog/:slug',                          :controller => 'blogs',            :action => 'show',                :as => 'blog_show'
    
  match 'my/messages/inbox',                                :controller => 'messages',         :action => 'inbox',               :as => 'messages_inbox'
  match 'my/messages/preview',                              :controller => 'messages',         :action => 'preview',             :as => 'messages_preview'
  match 'my/messages/inbox/:slug',                          :controller => 'messages',         :action => 'read_inbox',          :as => 'message_read_inbox'
  match 'my/messages/inbox/delete/:slug',                   :controller => 'messages',         :action => 'delete_inbox',        :as => 'message_delete_inbox'
  match 'my/messages/inbox/destroy/:slug',                  :controller => 'messages',         :action => 'destroy_inbox',       :as => 'message_destroy_inbox'
  match 'my/messages/outbox',                               :controller => 'messages',         :action => 'outbox',              :as => 'messages_outbox'
  match 'my/messages/new',                                  :controller => 'messages',         :action => 'new',                 :as => 'message_new'
  match 'my/messages/reply/:slug',                          :controller => 'messages',         :action => 'reply',               :as => 'message_reply'
  match 'my/messages/outbox/:slug',                         :controller => 'messages',         :action => 'read_outbox',         :as => 'message_read_outbox'
  match 'my/messages/outbox/delete/:slug',                  :controller => 'messages',         :action => 'delete_outbox',       :as => 'message_delete_outbox'
  match 'my/messages/outbox/destroy/:slug',                 :controller => 'messages',         :action => 'destroy_outbox',      :as => 'message_destroy_outbox'
  
  match 'my/friends/accept/:id',                            :controller => 'pendings',         :action => 'accept',              :as => 'friend_accept'
  match 'my/friends/ignore/:id',                            :controller => 'pendings',         :action => 'ignore',              :as => 'friend_ignore' 
  match 'my/friends/list.:format',                          :controller => 'friends',          :action => 'list',                :as => 'friend_list'
  match 'my/friends/requested',                             :controller => 'pendings',         :action => 'requested',           :as => 'friend_requested'
  match 'my/friends/requests',                              :controller => 'pendings',         :action => 'index',               :as => 'friend_requests' 
  match 'my/friends/request/:profilename',                  :controller => 'friends',          :action => 'req',                 :as => 'friend_request'
  
  match ':profilename/portrait/new',                        :controller => 'portrait',         :action => 'new',                 :as => 'portrait_new'
  match ':profilename/portrait/create',                     :controller => 'portrait',         :action => 'create',              :as => 'portrait_create'
  match ':profilename/portrait/delete',                     :controller => 'portrait',         :action => 'delete',              :as => 'portrait_delete'
  match ':profilename/portrait/destroy',                    :controller => 'portrait',         :action => 'destroy',             :as => 'portrait_destroy'
  
  match ':profilename/status/new',                          :controller => 'statuses',         :action => 'new',                 :as => 'status_new'
  match ':profilename/status/change',                       :controller => 'statuses',         :action => 'create',              :as => 'status_create'
  
  match ':profilename/photos',                              :controller => 'photos',           :action => 'show',                :as => 'photos_show'
  match ':profilename/photos/album/new',                    :controller => 'photos',           :action => 'album_new',           :as => 'album_new'
  match '/photos/album/create',                             :controller => 'photos',           :action => 'album_create',        :as => 'album_create'
  match ':profilename/photos/album/:slug',                  :controller => 'photos',           :action => 'album_show',          :as => 'album_show'
  match ':profilename/photos/album/:slug/organize',         :controller => 'photos',           :action => 'album_organize',      :as => 'album_organize'
  match ':profilename/photos/album/:slug/delete',           :controller => 'photos',           :action => 'album_delete',        :as => 'album_delete'
  match ':profilename/photos/album/:slug/deleteit',         :controller => 'photos',           :action => 'album_deleteit',      :as => 'album_deleteit'
  match ':profilename/photos/album/:slug/org',              :controller => 'photos',           :action => 'album_org',           :as => 'album_org'
  match '/photos/album/:slug/cover/:id',                    :controller => 'photos',           :action => 'album_cover',         :as => 'album_cover'
  match '/photos/album/:slug/newcover/:id',                 :controller => 'photos',           :action => 'album_newcover',      :as => 'album_change_cover'
  match '/photos/album/:slug/delete/:id',                   :controller => 'photos',           :action => 'photo_delete',        :as => 'photo_delete'
  match '/photos/album/:slug/deleteit/:id',                 :controller => 'photos',           :action => 'photo_deleteit',      :as => 'photo_deleteit'
  match ':profilename/photos/album/:slug/new',              :controller => 'photos',           :action => 'photo_new',           :as => 'photo_new'
  match ':profilename/photos/album/:slug/:id',              :controller => 'photos',           :action => 'photo_show',          :as => 'photo_show'
  match '/photos/create',                                   :controller => 'photos',           :action => 'photo_create',        :as => 'photo_create'

  match '/my/events',                                       :controller => 'events',           :action => 'my_events',           :as => 'profile_my_events'

app/models/pending.rb
class Pending
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :requester, :type => String
  index :requester, :unique => false
  field :requested, :type => String
  index :requested, :unique => false
  field :message
  
  attr_protected :_id

end

app/controllers/pendings_controller.rb
# coding: utf-8

class PendingsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @requests = Pending.find(:all, :conditions => { :requested => @current_profile.id.to_s })
    render :layout => 'my'
  end
  
  def requested
    @requests = Pending.find(:all, :conditions => { :requester => @current_profile.id.to_s })
    render :layout => 'my'
  end

  def new
  end

  def create
    if params[:pending][:requester] == @current_profile.id.to_s
      if Pending.create!(params[:pending])
        requested = Profile.find(params[:pending]['requested'])
        @flashcss = 'success'
        @flashmsg = "Se ha enviado correctamente tu petición como amigo a #{requested.name}."
      else
        @flashcss = 'error'
        @flashmsg = "Tu petición como amigo no se ha podido procesar, por favor intentalo más tarde."
      end
    else
      redirect_to :root
    end
  end

  def delete
  end

  def accept
    pending = Pending.find(params[:id])
    if pending.nil? 
      redirect_to :root
    else
      if pending.requested != @current_profile.id.to_s
        redirect_to :root
      else
        other_profile = Prof.find(pending.requester)
        if @current_profile.new_connection('Friend', other_profile, true) == true
          activity = Hash.new
          activity['action'] = 'friendship'
          activity['profile_id1'] = @current_profile.id.to_s
          activity['profile_id2'] = other_profile.id.to_s
          new_activity(activity)
          flash[:success] = "Has aceptado la petición como amigo de #{other_profile.name}."
          pending.destroy
          redirect_to friend_requests_url
        else
          flash[:error] = "La petición como amigo no se ha podido completar."
          redirect_to friend_requests_url
        end
      end
    end
  end
  
  def ignore
    pending = Pending.find(params[:id])
    if pending.nil? 
      redirect_to :root
    else
      if pending.requested != @current_profile.id.to_s
        redirect_to :root
      else
        other_profile = Prof.find(pending.requester)
        flash[:success] = "Has ignorado la petición como amigo de #{other_profile.name}."
        pending.destroy
        redirect_to friend_requests_url
      end
    end
  end

end

app/helpers/pendings_helper.rb
module PendingsHelper
end

app/views/pendings/create.js.erb
flashBar("<%= @flashmsg %>", "<%= @flashcss %>", {});

$('div#add_friend').fadeOut(100);
$('div#mask').fadeOut(300);
$('div#mWindow').fadeOut(300);
$('div#mWindowContent').fadeOut(300);

/*
$('div#mWindowContent').html('<p class="lh150 f150 tcenter w490 m10">Has enviado una petición como amigo a .<br /><br />asfdsf<br /></p>');
$('div#mWindow').animate({
	top: "+=80",
	height: $('div#mWindowContent').height() -160
});
$('div#mWindowContent').animate({
	top: "+=80",
	height: $('div#mWindowContent').height() -170
});
setTimeout('closeModal()', 10000);

function closeModal() {
	$('div#mask').fadeOut(300);
	$('div#mWindow').fadeOut(300);
	$('div#mWindowContent').fadeOut(300);
}

*/

app/views/pendings/delete.html.erb
<h1>Pendings#delete</h1>
<p>Find me in app/views/pendings/delete.html.erb</p>

app/views/pendings/index.html.erb
<% content_for :content do 
	 if @requests.count == 0 %>
		<p>No tienes peticiones de amigos</p>
	<% else %>
		<ul class="friends_box">
			<% @requests.each do |r| %>
			<% @profile = Prof.find(r.requester.to_s) %>
				<li class="friend">
					<div class="friend_portrait">
						<%= link_to image_tag('portal/portraits/avatar50.png', :class => 'portrait', :title => @profile.name),  profile_show_url(:profilename => @profile.profilename) %>

					</div>
					<div class="friend_info">
						<%= link_to @profile.name,  profile_show_url(:profilename => @profile.profilename) %>
						Realizó la petición el <%= l(r.created_at, :format => :long) %>
						<% if r.message %>
						<div class="friend_message">
							Te envía el siguiente mensaje:<br/>
							<%= simple_format r.message %>
						</div>
						<% end %>
					</div>
					<div class="friend_buttons">
						<%= link_to "Aceptar", friend_accept_url(:id => r.id.to_s), :class => 'button' %>
						<%= link_to "Ignorar", friend_ignore_url(:id => r.id.to_s), :class => 'button' %>
					</div>
					<div class="clearfix"></div>
				</li>
			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/pendings/new.html.erb
<h1>Pendings#new</h1>
<p>Find me in app/views/pendings/new.html.erb</p>

app/views/pendings/requested.html.erb
<% content_for :content do 
	 if @requests.count == 0 %>
		<p>No tienes peticiones a amigos pendientes de ser respondidas</p>
	<% else %>
		<ul class="friends_box">
			<% @requests.each do |r| %>
			<% @profile = Profile.find(r.requested.to_s) %>
				<li class="friend">
					<div class="friend_portrait">
						<%= link_to image_tag('portal/avatars/avatar50.png', :class => 'portrait', :title => @profile.name),  profile_show_url(:profilename => @profile.profilename) %>
					</div>
					<div class="friend_info">
						<%= link_to @profile.name,  profile_show_url(:profilename => @profile.profilename) %>
						Realizaste la petición el <%= l(r.created_at, :format => :long) %>
						<% if !r.message.nil? and r.message != "" %>
						<div class="friend_message">
							Enviaste el siguiente mensaje:<br/>
							<%= simple_format r.message %>
						</div>
						<% end %>
					</div>
					<div class="friend_buttons">
						<button id="<%#= f_cancel_my_url(@user.profilename) %>">Cancelar esta petición</button>
					</div>
					<div class="clearfix"></div>
				</li>
			<% end %>
		</ul>
	<% end %>
<% end %>