config/routes.rb
Taradai::Application.routes.draw do

  get "placesprof/index"

  get "placesprof/new"

  get "placesprof/create"

  get "placesprof/edit"

  get "placesprof/update"

  get "placesprof/delete"

  get "placesprof/destroy"

  get "events/my_events_create"

  get "events/my_events_new"

  get "events/my_events_edit"

  get "events/my_events_update"

  get "events/my_events_delete"

  get "events/my_events_destroy"

  get "events/group_events"

  get "events/group_events_new"

  get "events/group_events_create"

  get "events/group_events_edit"

  get "events/group_events_update"

  get "events/group_events_delete"

  get "events/group_events_destroy"

  get "events/tendency_events"

  devise_for :users
  
  resources :profiles, :only => [:new, :create, :edit, :update]
  resources :pendings, :only => [:create, :delete]
  resources :messages, :only => [:create]
  
  match 'map',                                              :controller => 'maps',             :action => 'random',              :as => 'maps_random'
  match 'my/map(.:format)',                                 :controller => 'maps',             :action => 'query',               :as => 'maps_query'
  match 'my/localization(.:format)',                        :controller => 'maps',             :action => 'localization',            :as => 'maps_location'
  match 's',                                                :controller => 'search',           :action => 'form',                :as => 'search_form'
  match 's/results',                                        :controller => 'search',           :action => 'results',             :as => 'search_results'
  
  match 'my/locale/:locale',                                :controller => 'locale',           :action => 'change',              :as => 'locale'
  
  match 'my/netupdates.:format',                            :controller => 'network',          :action => 'updates',             :as => "network_updates"
  match ':profilename/updates.:format',                     :controller => 'prof',             :action => 'updates',             :as => "profile_updates"
  
  match 'my/notifications/preview',                         :controller => 'notifications',    :action => 'preview',             :as => 'notifications_preview'
  match 'my/notifications',                                 :controller => 'notifications',    :action => 'index',               :as => 'notifications_index'
    
  
  match 'my/blog',                                          :controller => 'blogs',            :action => 'index',               :as => 'blog_my'
  match 'my/blog/new',                                      :controller => 'blogs',            :action => 'new',                 :as => 'blog_new'
  match 'my/blog/create',                                   :controller => 'blogs',            :action => 'create',              :as => 'blog_create'
  match 'my/blog/:slug/',                                   :controller => 'blogs',            :action => 'read',                :as => 'blog_read'
  match 'my/blog/:slug/edit',                               :controller => 'blogs',            :action => 'edit',                :as => 'blog_edit'
  match 'my/blog/:slug/update',                             :controller => 'blogs',            :action => 'update',              :as => 'blog_update'
  match 'my/blog/:slug/delete',                             :controller => 'blogs',            :action => 'delete',              :as => 'blog_delete'
  match 'my/blog/:slug/destroy',                            :controller => 'blogs',            :action => 'destroy',             :as => 'blog_destroy'
  
  match ':profilename/blog',                                :controller => 'blogs',            :action => 'browse',              :as => 'blogs_show'
  match ':profilename/blog/:slug',                          :controller => 'blogs',            :action => 'show',                :as => 'blog_show'
    
  match 'my/messages/inbox',                                :controller => 'messages',         :action => 'inbox',               :as => 'messages_inbox'
  match 'my/messages/preview',                              :controller => 'messages',         :action => 'preview',             :as => 'messages_preview'
  match 'my/messages/inbox/:slug',                          :controller => 'messages',         :action => 'read_inbox',          :as => 'message_read_inbox'
  match 'my/messages/inbox/delete/:slug',                   :controller => 'messages',         :action => 'delete_inbox',        :as => 'message_delete_inbox'
  match 'my/messages/inbox/destroy/:slug',                  :controller => 'messages',         :action => 'destroy_inbox',       :as => 'message_destroy_inbox'
  match 'my/messages/outbox',                               :controller => 'messages',         :action => 'outbox',              :as => 'messages_outbox'
  match 'my/messages/new',                                  :controller => 'messages',         :action => 'new',                 :as => 'message_new'
  match 'my/messages/reply/:slug',                          :controller => 'messages',         :action => 'reply',               :as => 'message_reply'
  match 'my/messages/outbox/:slug',                         :controller => 'messages',         :action => 'read_outbox',         :as => 'message_read_outbox'
  match 'my/messages/outbox/delete/:slug',                  :controller => 'messages',         :action => 'delete_outbox',       :as => 'message_delete_outbox'
  match 'my/messages/outbox/destroy/:slug',                 :controller => 'messages',         :action => 'destroy_outbox',      :as => 'message_destroy_outbox'
  
  match 'my/friends/accept/:id',                            :controller => 'pendings',         :action => 'accept',              :as => 'friend_accept'
  match 'my/friends/ignore/:id',                            :controller => 'pendings',         :action => 'ignore',              :as => 'friend_ignore' 
  match 'my/friends/list.:format',                          :controller => 'friends',          :action => 'list',                :as => 'friend_list'
  match 'my/friends/requested',                             :controller => 'pendings',         :action => 'requested',           :as => 'friend_requested'
  match 'my/friends/requests',                              :controller => 'pendings',         :action => 'index',               :as => 'friend_requests' 
  match 'my/friends/request/:profilename',                  :controller => 'friends',          :action => 'req',                 :as => 'friend_request'
  
  match ':profilename/portrait/new',                        :controller => 'portrait',         :action => 'new',                 :as => 'portrait_new'
  match ':profilename/portrait/create',                     :controller => 'portrait',         :action => 'create',              :as => 'portrait_create'
  match ':profilename/portrait/delete',                     :controller => 'portrait',         :action => 'delete',              :as => 'portrait_delete'
  match ':profilename/portrait/destroy',                    :controller => 'portrait',         :action => 'destroy',             :as => 'portrait_destroy'
  
  match ':profilename/status/new',                          :controller => 'statuses',         :action => 'new',                 :as => 'status_new'
  match ':profilename/status/change',                       :controller => 'statuses',         :action => 'create',              :as => 'status_create'
  
  match ':profilename/photos',                              :controller => 'photos',           :action => 'show',                :as => 'photos_show'
  match ':profilename/photos/album/new',                    :controller => 'photos',           :action => 'album_new',           :as => 'album_new'
  match '/photos/album/create',                             :controller => 'photos',           :action => 'album_create',        :as => 'album_create'
  match ':profilename/photos/album/:slug',                  :controller => 'photos',           :action => 'album_show',          :as => 'album_show'
  match ':profilename/photos/album/:slug/organize',         :controller => 'photos',           :action => 'album_organize',      :as => 'album_organize'
  match ':profilename/photos/album/:slug/delete',           :controller => 'photos',           :action => 'album_delete',        :as => 'album_delete'
  match ':profilename/photos/album/:slug/deleteit',         :controller => 'photos',           :action => 'album_deleteit',      :as => 'album_deleteit'
  match ':profilename/photos/album/:slug/org',              :controller => 'photos',           :action => 'album_org',           :as => 'album_org'
  match '/photos/album/:slug/cover/:id',                    :controller => 'photos',           :action => 'album_cover',         :as => 'album_cover'
  match '/photos/album/:slug/newcover/:id',                 :controller => 'photos',           :action => 'album_newcover',      :as => 'album_change_cover'
  match '/photos/album/:slug/delete/:id',                   :controller => 'photos',           :action => 'photo_delete',        :as => 'photo_delete'
  match '/photos/album/:slug/deleteit/:id',                 :controller => 'photos',           :action => 'photo_deleteit',      :as => 'photo_deleteit'
  match ':profilename/photos/album/:slug/new',              :controller => 'photos',           :action => 'photo_new',           :as => 'photo_new'
  match ':profilename/photos/album/:slug/:id',              :controller => 'photos',           :action => 'photo_show',          :as => 'photo_show'
  match '/photos/create',                                   :controller => 'photos',           :action => 'photo_create',        :as => 'photo_create'

  match '/my/events',                                       :controller => 'events',           :action => 'my_events',           :as => 'profile_my_events'

app/models/group.rb
class Group < ActAsGraph
  include Mongoid::Document

  field :name,          :type => String
  field :slug,          :type => String
  index :slug
  field :private,       :type => Boolean, :default => false
  field :description,   :type => String
  field :owner_id,      :type => String
  
  #mount_uploader :gportrait, GportraitUploader
  field :gportrait
  
  validates_length_of :name, :within => 4..50
  
  embeds_one :gforum
  
  embeds_many :activities
  
  def slugit!
    name = self.name
    if name == "new"
      name = "new1"
    end
    self.slug = find_unique_slug(name)
    if self.save!
      return true
    else
      return false
    end
  end
  
  private 
  
  def find_unique_slug(subject, suffix = '')
    slug = ("#{subject} #{suffix}").parameterize
    if Group.where(:slug => slug).count == 0
      slug
    else
      if Group.where(:slug => slug).first == self
        slug
      else
        if suffix == ''
          suffix = 1
        else
          suffix = suffix.to_i + 1
        end
        find_unique_slug(subject, suffix)
      end
    end
  end  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/applies.html.erb
<% content_for :main do %>
	<% if @applies.count > 0%>
		<ul class="friends">
			<% @applies.each do |a| %>
				<% prof = Prof.find(a.prof_id) %>
				<li>
					<div class="left w80 m10"><%= link_to image_tag(file_path(prof.portrait, 'portrait', '50'), :alt=> prof.name, :type => "p50"), profile_show_url(:profilename => prof.profilename) %></div>
					<div class="left w440 f105 m10"><%= link_to prof.name, profile_show_url(:profilename => prof.profilename) %>
						<br />
						<div class="left">Mensaje:</div>
						<div id="hideable" class="right">
							<%= link_to "Aceptar", group_apply_accept_url(:slug => @group.slug, :prof => prof.id.to_s) %> · <%= link_to "Ignorar", group_apply_ignore_url(:slug => @group.slug, :prof => prof.id.to_s) %>
						</div>
						<br />
						<% if a.message == "" %>
							<% message = "El usuario no ha escrito ningún mensaje." %>
						<% else %>
							<% message = a.message %>
						<% end %>
						<div class="left w420 color8 fcolor1 radius4 p10 mb5"><%= message %></div>
						<br/>

					</div>
					<div class="clear"></div>
				</li>
			<% end %>
		</ul>
	<% else %>
		<%= "No hay peticiones como miembro pendientes." %>
	<% end %>
<% end %>

app/views/groups/apply.html.erb
<% content_for :content do %>
<div class="w470">
	<%= simple_form_for(@gpending, :url => group_apply_create_url(:slug => params[:slug])) do |f| %>
	<div class="w460 radius4 green0f green4b f130 lh130 p5 mr0">¿Quieres unirte al grupo: <strong><%= @group.name %></strong>?</div>
	<div class="w460 fcolor8 f110 lh110 mt10"><p>El administrador del grupo debe confirmar tu solicitud antes de formar parte del mismo.<br/>Déjale un mensaje si lo deseas.</p></div>
	
	<div class="w460 fcolor9 f110 lh110 mt10">
		<div class="w70 mr10 tright left"><strong>Mensaje</strong></div>
	
		<div class="w370 right">
			<%= f.text_area :message, :style => "width:370px; height:90px" %>
		</div>
	</div>
	<div class="clear"></div>
	<div class="mt10 w470">
		<div class="right">
	<input type="button" value="Cancelar" class="close" />
	<%= f.submit :class => 'ml10' %>
		</div>
	</div>
	<% end %>
	<div class="clear"></div>
</div>
<% end %>

app/views/groups/browse.html.erb
<% content_for :content do %>
		<ul class="friends">
			<% @groups.each do |g| %>
				<li style="height:70px; border-bottom:1px #aaa solid;">
					<div class="left w80 m10"><%= link_to image_tag(file_path(g.gportrait, 'gportrait', '50'), :alt=> g.name, :type=> 'p50'), group_show_url(:slug => g.slug) %></div>
					<div class="left w500 f105 m10"><%= link_to g.name, group_show_url(:slug => g.slug) %><br/>
						<div id="hideable" class="right">
							<% if g.owner_id == @current_profile.id.to_s %>
								<%= link_to "Editar", group_edit_url(:slug => g.slug) %> · 
							<% end %>
							<%= link_to "Ver", group_show_url(:slug => g.slug) %>
					</div>
				</li>
				<div class="clear"></div>
			<% end %>
		</ul>
<% end %>

app/views/groups/edit.html.erb
<% content_for :content do %>
	<%= simple_form_for @group, :url => group_update_url do |f| %>
		<%= f.input :name, :label => 'Nombre:', :hint => 'Escribe el nombre del grupo.', :required => true, :input_html => { :maxlength => 50, :class=> 'w440' } %>
		<div class="input string optional">
		<%= f.label :description %><%= f.text_area :description, :rows => 6, :class => 'w440' %>
		</div>
		<div class="input string optional"><%= f.label :private %>
		<%= f.collection_radio :private, [[false, 'Grupo público'], [true, 'Grupo privado']], :first, :last %>
		</div>
		<div class="clear right w460 mb10">
		<span class="hint" style="margin-left:0px;">· Un <strong>grupo público</strong> permite a todos los usuarios unirse a él sin aprobación por el creador del grupo.<br/>· Los <strong>grupos privados</strong> requiren autorización/invitación para formar parte de ellos.</span>
		</div>
		<div class="clear"></div>
		<div class="mr10 ml10 w120 tright b left">Tendencias relacionadas:</div>
		<div class="left w440">
			<% @tendencies.each do |t| %>
				<% if t.connected?('GTend', @group) %>
					<%= check_box("t", "#{t.id.to_s}", :checked => true) %> <%= t.name[session['locale']] %><br />
				<% else %>
					<%= check_box("t", "#{t.id.to_s}") %> <%= t.name[session['locale']] %><br />
				<% end %>
			<% end %>
			<span class="hint" style="margin-left:0px;">Selecciona la/s tendencia/s que trabajais en el grupo.</span> 
		</div>
		<div class="clear right">
			<%= f.submit %>
		</div>
		
	<% end %>
<% end %>

app/views/groups/join.html.erb
<% content_for :content do %>
<div class="w470">
	
	<div class="w460 radius4 green0f green4b f130 lh130 p5 mr0">¿Quieres unirte al grupo: <strong><%= @group.name %></strong>?</div>
	<div class="w460 fcolor8 f110 lh110 mt10"><p>Este grupo es público y todo el mundo puede unirse si lo desea.</p></div>
	<div class="clear"></div>
	<div class="mt10 w470">
		<div class="right">
	<input type="button" value="Cancelar" class="close" />
	<%= link_to "Si", group_join_create_url(:slug => @group.slug), :class => 'button' %>
		</div>
	</div>
	
	<div class="clear"></div>
</div>
<% end %>

app/views/groups/members.html.erb
<% content_for :main do %>
		<ul class="friends">
			<% @members.each do |m| %>
				<li style="height:70px; border-bottom:1px #aaa solid;">
					<div class="left w80 m10"><%= link_to image_tag(file_path(m.portrait, 'portrait', '50'), :alt=> m.name, :type => "p50"), profile_show_url(:profilename => m.profilename) %></div>
					<div class="left w440 f105 m10"><%= link_to m.name, profile_show_url(:profilename => m.profilename) %>
						<% if m.id.to_s == @group.owner_id %>
							<%= " (creador)" %>
						<% end %>
						<br/>
						<div id="hideable" class="right">
						<% if m != @current_profile and @current_profile.connected?('Friend', m) == false %>
							<%= link_to 'Añadir como amigo', friend_request_url(:profilename => m.profilename), :type => 'modal' %>
						<% end %>
						</div>
					</div>
				</li>
				<div class="clear"></div>
			<% end %>
		</ul>
<% end %>

app/views/groups/new.html.erb
<% content_for :content do %>
	<%= simple_form_for @group, :url => group_create_url do |f| %>
		<%= f.input :name, :label => 'Nombre:', :hint => 'Escribe el nombre del grupo.', :required => true, :input_html => { :maxlength => 50, :class=> 'w440' } %>
		<div class="input string optional">
		<%= f.label :description %><%= f.text_area :description, :rows => 6, :class => 'w440' %>
		</div>
		<div class="input string optional"><%= f.label :private %>
		<%= f.collection_radio :private, [[false, 'Grupo público'], [true, 'Grupo privado']], :first, :last %>
		</div>
		<div class="clear right w460 mb10">
		<span class="hint" style="margin-left:0px;">· Un <strong>grupo público</strong> permite a todos los usuarios unirse a él sin aprobación por el creador del grupo.<br/>· Los <strong>grupos privados</strong> requiren autorización/invitación para formar parte de ellos.</span>
		</div>
		<div class="clear"></div>
		<div class="mr10 ml10 w120 tright b left">Tendencias relacionadas:</div>
		<div class="left w440">
			<% @tendencies.each do |t| %>
				<%= check_box("t", "#{t.id.to_s}") %> <%= t.name[session['locale']] %><br />
			<% end %>
			<span class="hint" style="margin-left:0px;">Selecciona la/s tendencia/s que trabajais en el grupo.</span> 
		</div>
		<div class="clear right">
			<%= f.submit %>
		</div>
		
	<% end %>
<% end %>

app/views/groups/portrait.html.erb
<% content_for :content do %>
<script src="/javascripts/uploadify/swfobject.js" type="text/javascript"></script>
<script src="/javascripts/uploadify/jquery.uploadify.v2.1.4.min.js" type="text/javascript"></script>
<div class="w470">
	<div class="w460 radius4 green0f green4b f130 lh130 p5 mr0">Cambio de foto del perfil del grupo</div>
	<div class="w460 fcolor8 f110 lh110 mt10"><p>Por favor pulsa el botón 'Subir foto' para comenzar el cambio de la foto del grupo. Una vez seleccionado el fichero subirá al servidor y realizará el cambio automáticamente.</p></div>
	
	<script type="text/javascript">
	$(function() {
		$('#custom_file_upload').uploadify({
			'uploader'       : '/javascripts/uploadify/uploadify.swf',
			'script'         : '<%= group_portrait_create_url(:slug => @group.slug) %>',
			'scriptData'     : {
				'authenticity_token'      : encodeURIComponent('<%= u form_authenticity_token if protect_against_forgery? %>'),
				'user'                    : '<%= @current_profile.profilename %>' ,
				"<%= key = Rails.application.config.session_options[:key] %>" : "<%= cookies[key] %>"
			}, 
			'cancelImg'      : '/javascripts/uploadify/cancel.png',
			'multi'          : false,
			'auto'           : true,
			'fileExt'        : '*.jpg;*.gif;*.png',
			'fileDesc'       : 'Image Files (.JPG, .GIF, .PNG)',
			'queueID'        : 'custom-queue',
			'queueSizeLimit' : 1,
			'simUploadLimit' : 1,
			'displayData'    : 'percentage',
			'sizeLimit'      : <%= 5.megabytes %>,
			'removeCompleted': false,
			'onSelectOnce'   : function(event,data) { 
				$('#status-message').text(data.filesSelected + ' foto/s añadida/s a la cola de subida.');
			},
			'onAllComplete'  : function(event,data) { 
				setTimeout(jump(), 500);
			}
		});
	});
	
	function jump() {
		window.location = '<%= group_show_url(:slug => @group.slug) %>';
	}
	
	</script>
	<style type="text/css">
		#custom-demo .uploadifyQueueItem {  background-color: #FFFFFF;  border: none;  border-bottom: 1px solid #E5E5E5;  font: 11px Verdana, Geneva, sans-serif;  height: 50px;  margin-top: 0;  padding: 10px;  width: 350px; }
		#custom-demo .uploadifyError {  background-color: #FDE5DD !important;  border: none !important;  border-bottom: 1px solid #FBCBBC !important;}
		#custom-demo .uploadifyQueueItem .cancel {  float: right;}
		#custom-demo .uploadifyQueue .completed {  color: #C5C5C5;}
		#custom-demo .uploadifyProgress {  background-color: #E5E5E5;  margin-top: 10px;  width: 100%;}
		#custom-demo .uploadifyProgressBar {  background-color: #0099FF;  height: 3px;  width: 1px;}
		#custom-demo #custom-queue {  border: 1px solid #E5E5E5;  height: 73px;margin-bottom: 10px;  width: 390px; overflow:scroll;}
	</style>
	<div class="w460 fcolor9 f110 lh110 mt10" id="custom-demo">
		<div class="demo-box">
			<div id="status-message">Selecciona la foto que quieres usar.</div>
			<div id="custom-queue" class="uplodifyQueue"></div>
			<input id="custom_file_upload" type="file", name="photofile" style="display: none;" />
		</div>
	</div>
	<div class="clear"></div>
	<div class="mt10 w470">
		<div class="right">
			<%= link_to 'Cancelar', "#", :class => "button close" %>
		</div>
	</div>

	<div class="clear"></div>
</div>
<% end %>

app/views/groups/profile_show.html.erb
<% content_for :main do %>
		<ul class="friends">
			<% @groups.each do |g| %>
				<li style="height:70px; border-bottom:1px #aaa solid;">
					<div class="left w80 m10"><%= link_to image_tag(file_path(g.gportrait, 'gportrait', '50'), :alt=> g.name, :type=> 'p50'), group_show_url(:slug => g.slug) %></div>
					<div class="left w440 f105 m10"><%= link_to g.name, group_show_url(:slug => g.slug) %></div>
				</li>
				<div class="clear"></div>
			<% end %>
		</ul>
<% end %>

app/views/groups/show.html.erb
<% content_for :main do %>
	<% if @group.private == true and @current_profile.connected?('GMember', @group) == false %>
		<% if Gpending.where(:group_id => @group.id.to_s, :prof_id => @current_profile.id.to_s).count == 1 %>
			<div class="m10 tcenter">
				<br/>
			Este grupo es privado, únicamente los miembros del mismo pueden ver su contenido. <br /> <br/ >
			Has solicitado acceso a este grupo, debes esperar a que el creador del mismo te de acceso.
			<hr />
			</div>
		<% else %>
			<div class="m10 tcenter">
				<br/>
			Este grupo es privado, únicamente los miembros del mismo pueden ver su contenido. <br /> 
			Si deseas formar parte de este grupo puedes hacer una solicitud de acceso.
			<hr />
			<%= link_to "Solicitar acceso", group_apply_url(:slug => @group.slug), :class => 'button', :type => 'modal' %>
			</div>
		<% end %>
	<% else %>
	<ul id="activities">
		<%= "#{@activities.count} actividades" %>
		<% @activities.each do |activity|
			data = activity.activitydatas
			hash_data = Hash.new
			data.each do |d|
				hash_data[d.key] = d.data
			end
      
        
			case activity.action
			when "group"
			begin
				if hash_data['profile_id'] == session['current_profile']
					profile = @current_profile
				else
					profile = Prof.find(hash_data['profile_id'])
				end
				
				@group = Group.find(hash_data['group_id'])
				if profile.nil? == false and @group.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has creado este grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha creado este grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
				<% end
			rescue
		  end
				
			when "joingroup"
			begin
				if hash_data['profile_id'] == session['current_profile']
					profile = @current_profile
				else
					profile = Prof.find(hash_data['profile_id'])
				end
				
				@group = Group.find(hash_data['group_id'])
				if profile.nil? == false and @group.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Te has unido al grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> se ha unido al grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
				<% end
			rescue
		  end
			when "gportrait"
			begin
				if hash_data['profile_id'] == session['current_profile']
					profile = @current_profile
				else
					profile = Prof.find(hash_data['profile_id'])
				end
				
				@group = Group.find(hash_data['group_id'])
				if profile.nil? == false and @group.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has cambiado la foto de perfil del grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha cambiado la foto de perfil del grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
				<% end
			rescue
			end
			when "gforum"
			begin
				if hash_data['profile_id'] == session['current_profile']
					profile = @current_profile
				else
					profile = Prof.find(hash_data['profile_id'])
				end
				@group = Group.find(hash_data['group_id'])
				if profile.nil? == false and @group.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% @topic = @group.gforum.gtopics.find(hash_data['topic_id']) %>
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has escrito el mensaje '<%= link_to @topic.title, group_forum_topic_show_url(:slug => @group.slug, :tslug => @topic.slug) %>' en el foro del grupo.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha escrito el mensaje '<%= link_to @topic.title, group_forum_topic_show_url(:slug => @group.slug, :tslug => @topic.slug) %>' en el foro del grupo<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
				<% end 
				rescue
				end %>
			<% end %>	
		<% end %>
	</ul>
	<% end %>
<% end %>