config/routes.rb
Taradai::Application.routes.draw do

  get "placesprof/index"

  get "placesprof/new"

  get "placesprof/create"

  get "placesprof/edit"

  get "placesprof/update"

  get "placesprof/delete"

  get "placesprof/destroy"

  get "events/my_events_create"

  get "events/my_events_new"

  get "events/my_events_edit"

  get "events/my_events_update"

  get "events/my_events_delete"

  get "events/my_events_destroy"

  get "events/group_events"

  get "events/group_events_new"

  get "events/group_events_create"

  get "events/group_events_edit"

  get "events/group_events_update"

  get "events/group_events_delete"

  get "events/group_events_destroy"

  get "events/tendency_events"

  devise_for :users
  
  resources :profiles, :only => [:new, :create, :edit, :update]
  resources :pendings, :only => [:create, :delete]
  resources :messages, :only => [:create]
  
  match 'map',                                              :controller => 'maps',             :action => 'random',              :as => 'maps_random'
  match 'my/map(.:format)',                                 :controller => 'maps',             :action => 'query',               :as => 'maps_query'
  match 'my/localization(.:format)',                        :controller => 'maps',             :action => 'localization',            :as => 'maps_location'
  match 's',                                                :controller => 'search',           :action => 'form',                :as => 'search_form'
  match 's/results',                                        :controller => 'search',           :action => 'results',             :as => 'search_results'
  
  match 'my/locale/:locale',                                :controller => 'locale',           :action => 'change',              :as => 'locale'
  
  match 'my/netupdates.:format',                            :controller => 'network',          :action => 'updates',             :as => "network_updates"
  match ':profilename/updates.:format',                     :controller => 'prof',             :action => 'updates',             :as => "profile_updates"
  
  match 'my/notifications/preview',                         :controller => 'notifications',    :action => 'preview',             :as => 'notifications_preview'
  match 'my/notifications',                                 :controller => 'notifications',    :action => 'index',               :as => 'notifications_index'
    
  
  match 'my/blog',                                          :controller => 'blogs',            :action => 'index',               :as => 'blog_my'
  match 'my/blog/new',                                      :controller => 'blogs',            :action => 'new',                 :as => 'blog_new'
  match 'my/blog/create',                                   :controller => 'blogs',            :action => 'create',              :as => 'blog_create'
  match 'my/blog/:slug/',                                   :controller => 'blogs',            :action => 'read',                :as => 'blog_read'
  match 'my/blog/:slug/edit',                               :controller => 'blogs',            :action => 'edit',                :as => 'blog_edit'
  match 'my/blog/:slug/update',                             :controller => 'blogs',            :action => 'update',              :as => 'blog_update'
  match 'my/blog/:slug/delete',                             :controller => 'blogs',            :action => 'delete',              :as => 'blog_delete'
  match 'my/blog/:slug/destroy',                            :controller => 'blogs',            :action => 'destroy',             :as => 'blog_destroy'
  
  match ':profilename/blog',                                :controller => 'blogs',            :action => 'browse',              :as => 'blogs_show'
  match ':profilename/blog/:slug',                          :controller => 'blogs',            :action => 'show',                :as => 'blog_show'
    
  match 'my/messages/inbox',                                :controller => 'messages',         :action => 'inbox',               :as => 'messages_inbox'
  match 'my/messages/preview',                              :controller => 'messages',         :action => 'preview',             :as => 'messages_preview'
  match 'my/messages/inbox/:slug',                          :controller => 'messages',         :action => 'read_inbox',          :as => 'message_read_inbox'
  match 'my/messages/inbox/delete/:slug',                   :controller => 'messages',         :action => 'delete_inbox',        :as => 'message_delete_inbox'
  match 'my/messages/inbox/destroy/:slug',                  :controller => 'messages',         :action => 'destroy_inbox',       :as => 'message_destroy_inbox'
  match 'my/messages/outbox',                               :controller => 'messages',         :action => 'outbox',              :as => 'messages_outbox'
  match 'my/messages/new',                                  :controller => 'messages',         :action => 'new',                 :as => 'message_new'
  match 'my/messages/reply/:slug',                          :controller => 'messages',         :action => 'reply',               :as => 'message_reply'
  match 'my/messages/outbox/:slug',                         :controller => 'messages',         :action => 'read_outbox',         :as => 'message_read_outbox'
  match 'my/messages/outbox/delete/:slug',                  :controller => 'messages',         :action => 'delete_outbox',       :as => 'message_delete_outbox'
  match 'my/messages/outbox/destroy/:slug',                 :controller => 'messages',         :action => 'destroy_outbox',      :as => 'message_destroy_outbox'
  
  match 'my/friends/accept/:id',                            :controller => 'pendings',         :action => 'accept',              :as => 'friend_accept'
  match 'my/friends/ignore/:id',                            :controller => 'pendings',         :action => 'ignore',              :as => 'friend_ignore' 
  match 'my/friends/list.:format',                          :controller => 'friends',          :action => 'list',                :as => 'friend_list'
  match 'my/friends/requested',                             :controller => 'pendings',         :action => 'requested',           :as => 'friend_requested'
  match 'my/friends/requests',                              :controller => 'pendings',         :action => 'index',               :as => 'friend_requests' 
  match 'my/friends/request/:profilename',                  :controller => 'friends',          :action => 'req',                 :as => 'friend_request'
  
  match ':profilename/portrait/new',                        :controller => 'portrait',         :action => 'new',                 :as => 'portrait_new'
  match ':profilename/portrait/create',                     :controller => 'portrait',         :action => 'create',              :as => 'portrait_create'
  match ':profilename/portrait/delete',                     :controller => 'portrait',         :action => 'delete',              :as => 'portrait_delete'
  match ':profilename/portrait/destroy',                    :controller => 'portrait',         :action => 'destroy',             :as => 'portrait_destroy'
  
  match ':profilename/status/new',                          :controller => 'statuses',         :action => 'new',                 :as => 'status_new'
  match ':profilename/status/change',                       :controller => 'statuses',         :action => 'create',              :as => 'status_create'
  
  match ':profilename/photos',                              :controller => 'photos',           :action => 'show',                :as => 'photos_show'
  match ':profilename/photos/album/new',                    :controller => 'photos',           :action => 'album_new',           :as => 'album_new'
  match '/photos/album/create',                             :controller => 'photos',           :action => 'album_create',        :as => 'album_create'
  match ':profilename/photos/album/:slug',                  :controller => 'photos',           :action => 'album_show',          :as => 'album_show'
  match ':profilename/photos/album/:slug/organize',         :controller => 'photos',           :action => 'album_organize',      :as => 'album_organize'
  match ':profilename/photos/album/:slug/delete',           :controller => 'photos',           :action => 'album_delete',        :as => 'album_delete'
  match ':profilename/photos/album/:slug/deleteit',         :controller => 'photos',           :action => 'album_deleteit',      :as => 'album_deleteit'
  match ':profilename/photos/album/:slug/org',              :controller => 'photos',           :action => 'album_org',           :as => 'album_org'
  match '/photos/album/:slug/cover/:id',                    :controller => 'photos',           :action => 'album_cover',         :as => 'album_cover'
  match '/photos/album/:slug/newcover/:id',                 :controller => 'photos',           :action => 'album_newcover',      :as => 'album_change_cover'
  match '/photos/album/:slug/delete/:id',                   :controller => 'photos',           :action => 'photo_delete',        :as => 'photo_delete'
  match '/photos/album/:slug/deleteit/:id',                 :controller => 'photos',           :action => 'photo_deleteit',      :as => 'photo_deleteit'
  match ':profilename/photos/album/:slug/new',              :controller => 'photos',           :action => 'photo_new',           :as => 'photo_new'
  match ':profilename/photos/album/:slug/:id',              :controller => 'photos',           :action => 'photo_show',          :as => 'photo_show'
  match '/photos/create',                                   :controller => 'photos',           :action => 'photo_create',        :as => 'photo_create'

  match '/my/events',                                       :controller => 'events',           :action => 'my_events',           :as => 'profile_my_events'

app/models/tendency.rb
class Tendency < ActAsGraph
  include Mongoid::Document
  include Mongoid::Timestamps
  
  before_save :create_forum!
  
  field :slug, :type => String
  index :slug
  field :name, :type => Hash
  
  embeds_many :activities
  embeds_one :gforum
  
  def members(limit = 0)
    tendencies = self.connections('Tend', limit)
    if tendencies.nil?
      tendencies = []
    end
    return tendencies
  end
  
  def members_count
    return self.connections_count('Tend')
  end
  
  private 
  
  def create_forum!
    self.create_gforum
  end
end

app/controllers/tendencies_controller.rb
class TendenciesController < ApplicationController
  def show
    @tendency = Tendency.where(:slug => params[:name]).first
    if @tendency.nil?
      redirect_to :root
    else
      @activities = @tendency.activities.where(:locale => session['locale']).order_by(:created_at.desc).limit(40)
      @title = "#{@tendency.name[session['locale']]}"
      render :layout => "tendencies" 
    end
  end

  def blogs
    @tendency = Tendency.where(:slug => params[:name]).first
    if @tendency.nil?
      redirect_to :root
    else
      @blogs = @tendency.connections_sort_by_time('BTend', 0, 40, 'DESC')
      @title = "#{@tendency.name[session['locale']]}"
      render :layout => 'tendencies'
    end
  end

  def members
    @tendency = Tendency.where(:slug => params[:name]).first
    if @tendency.nil?
      redirect_to :root
    else
      @members = @tendency.members
      @title = "#{@tendency.name[session['locale']]}"
      render :layout => 'tendencies'
    end
  end

  def groups
    @tendency = Tendency.where(:slug => params[:name]).first
    if @tendency.nil?
      redirect_to :root
    else
      @groups = @tendency.connections('GTend')
      @title = "#{@tendency.name[session['locale']]}"
      render :layout => 'tendencies'
    end
  end
end

app/helpers/tendencies_helper.rb
module TendenciesHelper
end

app/views/tendencies/blogs.html.erb
<% content_for :main do %>
<ul class="friends">
<% @blogs.each do |blog| %>
	<% profile = Prof.find(blog.prof_id) %>
	<% if blog.privacy == true
		 if profile == @current_profile or profile.connected?('Friend', @current_profile) == true 
			show = true
		else
			show = false
		end
	else
		show = true
	end %>
			
	<% if show == true and blog.published == true %>	
	<li>
<div class="color0 radius4 mb20">
	<div class="p10">
		<h3><%= blog.title %></h3><hr />
		<div class="mb10"><%= sanitize(blog.body, :tags => %w(br))[0..100] %></div>
		<hr />
		<div class="left"><p><%= l(blog.updated_at, :format => :short) %></p></div>
		<div id="hideable" class="right">
			<%= link_to "Leer el artículo completo ...", blog_show_url(:profilename => profile.profilename, :slug => blog.slug) %>
			<% if profile == @current_profile %>
				<%= " | " %><%= link_to "Editar", blog_edit_path(:slug => blog.slug) %> | <%= link_to "Eliminar", blog_delete_url(:slug => blog.slug), :class => 'modal' %>
			<% end %>
		</div>
	</div>
	<div class="clear"></div>
</div>	
	</li>
	<% end %>
<% end %>
</ul>
<p><%= "Blogs = " + @blogs.count.to_s %></p>

<% end %>

app/views/tendencies/forum.html.erb
<h1>Tendencies#forum</h1>
<p>Find me in app/views/tendencies/forum.html.erb</p>

app/views/tendencies/groups.html.erb
<% content_for :main do %>
		<ul class="friends">
			<% @groups.each do |g| %>
				<li style="height:70px; border-bottom:1px #aaa solid;">
					<div class="left w80 m10"><%= link_to image_tag(file_path(g.gportrait, 'gportrait', '50'), :alt=> g.name, :type=> 'p50'), group_show_url(:slug => g.slug) %></div>
					<div class="left w440 f105 m10"><%= link_to g.name, group_show_url(:slug => g.slug) %></div>
				</li>
				<div class="clear"></div>
			<% end %>
		</ul>
<% end %>

app/views/tendencies/members.html.erb
<% content_for :main do %>
		<ul class="friends">
			<% @members.each do |f| %>
				<li style="height:70px; border-bottom:1px #aaa solid;">
					<div class="left w80 m10"><%= link_to image_tag(file_path(f.portrait, 'portrait', '50'), :alt=> f.name), profile_show_url(:profilename => f.profilename) %></div>
					<div class="left w440 f105 m10"><%= link_to f.name, profile_show_url(f.profilename) %></div>
				</li>
				<div class="clear"></div>
			<% end %>
		</ul>
<% end %>

app/views/tendencies/show.html.erb
<% content_for :main do %>
<ul id="activities">
	<%= "#{@activities.count} actividades" %>
	<% @activities.each do |activity|
		data = activity.activitydatas
		hash_data = Hash.new
		data.each do |d|
			hash_data[d.key] = d.data
		end
		
		case activity.action
		when "blog"
		  begin
			if hash_data['profile_id'] == session['current_profile']
				profile = @current_profile
			else
				profile = Prof.find(hash_data['profile_id'])
			end
			
			@blog = Blog.find(hash_data['blog_id'])
			if profile.nil? == false and @blog.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has escrito el artículo titulado: <%= link_to @blog.title, blog_show_url(:profilename => profile.profilename, :slug => @blog.slug) %>.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha escrito el artículo titulado: <%= link_to @blog.title, blog_show_url(:profilename => profile.profilename, :slug => @blog.slug) %>.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
			<% end
			rescue
			end
		when "group"
		  begin
			if hash_data['profile_id'] == session['current_profile']
				profile = @current_profile
			else
				profile = Prof.find(hash_data['profile_id'])
			end
			@group = Group.find(hash_data['group_id'])
			if profile.nil? == false and @group.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has creado el grupo: <%= link_to @group.name, group_show_url(:slug => @group.slug) %>.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha creado el grupo: <%= link_to @group.name, group_show_url(:slug => @group.slug) %>.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
			<% end
			rescue
			end
		when "tforum"
		  begin
			if hash_data['profile_id'] == session['current_profile']
				profile = @current_profile
			else
				profile = Prof.find(hash_data['profile_id'])
			end
			@topic = @tendency.gforum.gtopics.find(hash_data['topic_id'])
			if profile.nil? == false and @topic.nil? == false %>
					<li id="<%= activity.id.to_s %>">
						<div class="left w530">
						<div class="left w50 p10">
							<%= link_to image_tag(file_path(profile.portrait, 'portrait', '50'), :alt => profile.name, :type => "p50"), profile_show_url(:profilename => profile.profilename) %>
						</div>						
						<div class="m10 w420">
						<% if hash_data["profile_id"] == session["current_profile"]%>
						<p>Has escrito el mensaje '<%= link_to @topic.title, tendencies_forum_topic_show_url(:name => @tendency.slug, :tslug => @topic.slug) %>' en el foro.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% else %>
						<p><%= link_to profile.name, profile_show_url(:profilename => profile.profilename) %> ha escrito el mensaje '<%= link_to @topic.title, tendencies_forum_topic_show_url(:name => @tendency.slug, :tslug => @topic.slug) %>' en el foro.<br/><span class="quiet">Hace <%= time_ago_in_words(activity.created_at) %></span></p>
						<% end %>
						</div>
						</div>
						<hr class="mb0" />
					</li>	
			<% end
			rescue
			end
		
		end  %>
	<% end %>
</ul>
<% end %>